name: Build and Push Image

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: go test ./...

  swagger:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Generate Swagger docs
        run: swag init

      - name: Save Swagger docs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: swagger-docs
          path: ./docs

  build:
    runs-on: ubuntu-latest
    needs: [test, swagger]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Swagger docs
        uses: actions/download-artifact@v3
        with:
          name: swagger-docs
          path: ./docs

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project-wraith:latest,${{ secrets.DOCKERHUB_USERNAME }}/project-wraith:${{ github.sha }}
