name: Build and Push Image

on:
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Go Get Dependencies
        run: go get

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Project
        run: go build -v ./...

      - name: Run Tests
        uses: robherley/go-test-action@v0

  swagger:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger Docs
        run: swag init

      - name: Save Swagger Docs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: swagger-docs
          path: ./docs

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test, swagger, setup]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Environment Variables
        run: |
          # Determine the environment based on the branch
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "${{ secrets.ENV_MAIN }}" > .env
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "${{ secrets.ENV_DEV }}" > .env
          fi

      - name: Verify Environment Variables
        run: |
          cat .env

      - name: Restore Swagger Docs
        uses: actions/download-artifact@v3
        with:
          name: swagger-docs
          path: ./docs

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/project-wraith:${{ github.sha }}_${{ github.ref == 'refs/heads/dev' && 'beta' || 'release' }}
            ${{ secrets.DOCKERHUB_USERNAME }}/project-wraith:${{ github.sha }}_latest
